"""Deploy module 'energy': the energy screen, the energy flows and the energy-analysis dashboard.

Run from the filled-in folder (output of tools/fill.py), with HA_URL and HA_TOKEN set (see ha_api.py):
  uv run --with-requirements requirements.txt python energy/deploy.py [--dry-run] [--no-dashboards]

Steps:
  1. uploads packages/energy.yaml (helpers of the flows view) to /config/packages/, checks the configuration and
     reloads input_datetime and input_select; gives new helpers their start value once (module.yaml defaults:)
  2. writes the scripts (day back / forward / today) and the automation energy_flows_follow_today (config API)
  3. bundles www/analysis/config.js + core.js + the topics into www/energy-analysis.js (version = content hash) and
     uploads it, energy-screen.js and energy-flows.js to /config/www/ha-kit/energy/ as dashboard resources
  4. builds both dashboards from dashboard/config.json (dashboard/build.py) and saves them: the dashboard
     energy-analysis (views period, power, tariff, consumers, trends, battery; a view without its roles is left out)
     and the dashboard energy-screen (views energy and flows). A dashboard that does not exist is created (storage
     mode); the config of an existing one is saved to backup/ first and then replaced completely. Other dashboards
     are not touched. The url paths come from house.yaml energy.dashboards.
  5. reports the resources the dashboards need from elsewhere (cw-thema.js of base, tariff.js of a tariff module,
     HACS: apexcharts-card, power-flow-card-plus)
  --dry-run        prints every step, writes the bundle and the dashboard JSON into this folder (energy/www,
                   energy/dashboard/out) and never connects to Home Assistant
  --no-dashboards  steps 1-3 and 5 only (keep hand-made changes to the dashboards)
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE / "dashboard"))
import ha_api  # noqa: E402
import build as dashboard_build  # noqa: E402

FOLDER = "ha-kit/energy"
PACKAGE = HERE / "package.yaml"
PACKAGE_DST = f"{ha_api.CONFIG_DIR}/packages/energy.yaml"
DEFAULTS = yaml.safe_load((HERE / "module.yaml").read_text(encoding="utf-8")).get("defaults") or {}
TOPICS = ["base-load", "peak", "tariff", "consumers", "profiles", "battery"]
BUNDLE = HERE / "www" / "energy-analysis.js"
CARDS = [HERE / "www" / "energy-screen.js", HERE / "www" / "energy-flows.js"]
# Resources of other modules / HACS the dashboards use (path without ?v=, or a part of the URL for HACS).
NEEDS = {"/local/cw-thema.js": "module base (cw-kop, cw-chip, cw-metric, cw-status)",
         "apexcharts-card": "HACS frontend: apexcharts-card",
         "power-flow-card-plus": "HACS frontend: power-flow-card-plus"}


def make_bundle() -> str:
    """config.js + core.js + topics -> energy-analysis.js with VERSION = hash of the content; returns the version."""
    parts = [(HERE / "www" / "analysis" / f"{name}.js").read_text(encoding="utf-8") for name in ["config", "core", *TOPICS]]
    body = "\n".join(parts)
    version = hashlib.sha1(body.encode()).hexdigest()[:8]
    BUNDLE.write_text("// GENERATED by energy/deploy.py from www/analysis/*.js: edit those files (or house.yaml) instead.\n"
                      f'(() => {{ const VERSION = "{version}"; window.haKitEnergyBundle = VERSION; }})();\n' + body,
                      encoding="utf-8")
    if shutil.which("node"):
        r = subprocess.run(["node", "--check", str(BUNDLE)], capture_output=True, text=True)
        if r.returncode:
            sys.exit(f"energy-analysis.js does not parse:\n{r.stderr}")
    return version


def version_of(js: Path) -> str:
    text = js.read_text(encoding="utf-8")
    return text.split('const VERSION = "', 1)[1].split('"', 1)[0] if 'const VERSION = "' in text else "1"


def check_resources(resources: list[dict], cfg: dict) -> None:
    urls = [r["url"] for r in resources]
    needs = dict(NEEDS)
    if cfg["features"].get("tariff"):
        needs["/local/ha-kit/tariff/tariff.js"] = "the tariff module (tariff-be/deploy.py)"
    for part, who in needs.items():
        ok = any(u.split("?")[0] == part or part in u for u in urls)
        print(f"  resource {part}:", "present" if ok else f"MISSING: install {who}")


def save_dashboard(url_path: str, title: str, icon: str, config: dict) -> None:
    boards = ha_api.ws1({"type": "lovelace/dashboards/list"})
    if not any(b.get("url_path") == url_path for b in boards):
        ha_api.ws1({"type": "lovelace/dashboards/create", "url_path": url_path, "title": title, "icon": icon,
                    "mode": "storage", "show_in_sidebar": True, "require_admin": False})
        print("dashboard created:", url_path)
    else:
        r = ha_api.ws([{"type": "lovelace/config", "url_path": url_path}])[0]
        if r["success"]:
            backup = HERE / "backup" / f"dashboard-{url_path}-{date.today().isoformat()}.json"
            backup.parent.mkdir(exist_ok=True)
            if not backup.exists():
                backup.write_text(json.dumps(r["result"], indent=1, ensure_ascii=False), encoding="utf-8")
                print("backup:", backup)
    ha_api.ws1({"type": "lovelace/config/save", "url_path": url_path, "config": config})
    print(f"dashboard {url_path} saved:", ", ".join(v["path"] for v in config["views"]))


def main() -> None:
    dry = "--dry-run" in sys.argv
    with_dashboards = "--no-dashboards" not in sys.argv
    cfg = dashboard_build.load_config()
    version = make_bundle()
    built = dashboard_build.build(cfg) if with_dashboards else None
    names = cfg["dashboards"]
    if dry:
        print("dry run: nothing sent")
        print("  upload", PACKAGE.relative_to(HERE.parent), "->", PACKAGE_DST, "+ check_config + reload input_datetime, input_select")
        print("  defaults (new helpers only):", ", ".join(f"{k}={v}" for k, v in DEFAULTS.items()) or "none")
        print("  scripts + automations (config API):", HERE.name + "/scripts.yaml,", HERE.name + "/automations.yaml")
        print(f"  bundle {BUNDLE.relative_to(HERE.parent)} (v={version}) -> {ha_api.CONFIG_DIR}/www/{FOLDER}/ + resource")
        for js in CARDS:
            print(f"  upload {js.relative_to(HERE.parent)} -> {ha_api.CONFIG_DIR}/www/{FOLDER}/{js.name} + resource "
                  f"/local/{FOLDER}/{js.name}?v={version_of(js)}")
        on = sorted(k for k, v in cfg["features"].items() if v)
        print("  features on:", ", ".join(on) or "none")
        if built:
            paths = dashboard_build.write()
            print(f"  dashboard {names['analysis']}: {dashboard_build.summary(built['analysis'])}")
            print(f"  dashboard {names['screen']}: {dashboard_build.summary(built['screen'])}")
            print("  written:", ", ".join(str(p.relative_to(HERE.parent)) for p in paths.values()))
        print("  check resources:", ", ".join(NEEDS), "(+ tariff.js)" if cfg["features"].get("tariff") else "")
        return

    editor = ha_api.FileEditor()
    before = ha_api.entity_ids()
    editor.save(PACKAGE, PACKAGE_DST)
    ha_api.check_config()
    for domain in ("input_datetime", "input_select"):
        ha_api.rest(f"/api/services/{domain}/reload", {})
    ha_api.push_automations_and_scripts(HERE / "automations.yaml", HERE / "scripts.yaml")
    ha_api.set_defaults(DEFAULTS, before)
    for js in [BUNDLE, *CARDS]:
        ha_api.publish_card(js, FOLDER)
    if built:
        save_dashboard(names["analysis"], built["analysis"]["title"], "mdi:chart-timeline-variant", built["analysis"])
        save_dashboard(names["screen"], built["screen"]["title"], "mdi:lightning-bolt-outline", built["screen"])
    check_resources(ha_api.ws1({"type": "lovelace/resources"}), cfg)
    print("done. Open the dashboards and follow the test plan in energy/LOGIC.md.")


if __name__ == "__main__":
    main()
